swagger: '2.0'
info:
  title: Bank Argent API documentation - Transactions
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
  paths:
    /user/transaction:
      get:
        summary: Transaction
        description: API to get all transactions of the current month
        parameters:
        responses:
        "200" :
          description: Transaction data successfully obtained
          schema:
          $ref: '#/definitions/TransactionResponse'
        "400" :
          description: Bad Request 
        "401":
          description: No Authorization 
        "500" : 
          description: Internal Server Error