swagger: '2.0'
info:
  title: Bank Argent API documentation - Transactions
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
  paths:
  /transactions:
      get:
        summary: Transactions
        description: API to get all transactions of the current month
        parameters:
        responses:
        "200" :
          description: Transactions data successfully obtained
          schema:
          $ref: '#/definitions/TransactionsResponse'
        "400" :
          description: Bad Request 
        "401":
          description: No Authorization 
        "500" : 
          description: Internal Server Error
  /transactions/{transactionId}:
    get:
      summary: Transaction by id
      description: Return the details of a single transaction
      parameters:
         - name: transactionId
          in: path
          description: ID of transaction details to return
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Transaction data successfully obtained
          schema:
            $ref: '#/definitions/SingleTransactionResponse'
        "400" :
          description: Bad Request 
        "401":
          description: No Authorization 
        "500" : 
          description: Internal Server Error
    /transaction/{transactionId}/detail:
      post:
        security:
            - Bearer: []
        summary: Add information to a transaction
        description: API for Add information to a single transaction
        parameters:
          - in: body
            name: body
             description: Add Payload
          required: true
          schema:
            $ref: '#/definitions/AddDetail'
           - name: transactionId
          in: path
          description: ID of transaction detail to add
          required: true
          type: integer
          responses:
        "200":
          description: Transaction data successfully added
          schema:
            $ref: '#/definitions/AddDetailResponse'
        "400" :
          description: Bad Request 
        "401":
          description: No Authorization 
        "500" : 
          description: Internal Server Error
      put: 
        security:
          - Bearer: []
        summary: Edit information in a transaction
        description: API for Edit information in a single transaction
        parameters:
          - in: body
            name: body
            description: Edit Payload
            required: true
            schema:
               $ref: '#/definitions/EditDetail'
          - in: path
            name: transactionId          
            description: ID of transaction detail to edit
            required: true
            schema:
            type: integer
            
      delete:        
        security:
            - Bearer: []  
    

        



securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

