swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
tags: 
  - name: User Module
  - name: Transactions
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions:
    get:
      tags:
        - Transactions
      summary: Transactions
      description: API to get all transactions of the current month
      responses:
        "200" :
          description: Transactions data successfully obtained
          schema:
            $ref: '#/definitions/TransactionsResponse'
        "400" :
          description: Bad Request
          schema: 
            $ref: "#/definitions/BadRequestResponse"
        "401":
          description: No Authorization
          schema:
            $ref: "#/definitions/NoAuthResponse"
        "500" : 
          description: Internal Server Error
  /transactions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Transaction by id
      description: Return the details of a single transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of transaction details to return
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Transaction data successfully obtained
          schema:
            $ref: '#/definitions/SingleTransactionResponse'
        "400" :
          description: Bad Request 
          schema:
            $ref: "#/definitions/BadRequestResponse"
        "401":
          description: No Authorization
          schema:
            $ref: "#/definitions/NoAuthResponse" 
        "500" : 
          description: Internal Server Error
  /transaction/{transactionId}/detail:
    post:
      tags:
        - Transactions
      security:
        - Bearer: []
      summary: Add information to a transaction
      description: API for Add information to a single transaction
      parameters:
        - in: body
          name: body
          description: Add Payload
          required: true
          schema:
            $ref: '#/definitions/AddDetail'
        - in: path
          name: transactionId
          description: ID of transaction detail to add
          required: true
          type: integer
      responses:
        "200":
          description: Transaction data successfully added
          schema:
            $ref: '#/definitions/AddDetailResponse'
        "400" :
          description: Bad Request 
          schema:
            $ref: "#/definitions/BadRequestResponse"
        "401":
          description: No Authorization
          schema:
            $ref: "#/definitions/NoAuthResponse" 
        "500" : 
          description: Internal Server Error
    put: 
      tags:
        - Transactions
      security:
          - Bearer: []
      summary: Modify information in a transaction
      description: API for modify information in a single transaction
      parameters:
        - in: body
          name: body
          description: Modify Payload
          required: true
          schema:
            $ref: '#/definitions/PutDetail'
        - in: path
          name: transactionId          
          description: ID of transaction detail to modify
          required: true
          type: integer
      response: 
        "200":
          description: Transaction data successfully modified
          schema:
            $ref: '#/definitions/PutDetailResponse'
        "400" :
          description: Bad Request
          schema:
            $ref: "#/definitions/BadRequestResponse" 
        "401":
          description: No Authorization 
          schema:
            $ref: "#/definitions/NoAuthResponse"
        "500" : 
          description: Internal Server Error    
    delete:
      tags:
        - Transactions
      security:
        - Bearer: []
      summary: Delete information in a transaction
      description: API for delete information in a single transaction
      parameters:
        - in: body
          name: body
          description: Delete Payload
          required: true
          schema:
            $ref: '#/definitions/DeleteDetail'
        - in: path
          name: transactionId          
          description: ID of transaction detail to delete
          required: true
          type: integer
      response: 
        "200":
          description: Transaction data successfully deleted
          schema:
            $ref: '#/definitions/DeleteDetailResponse'
        "400" :
          description: Bad Request 
          schema:
            $ref: "#/definitions/BadRequestResponse"
        "401":
          description: No Authorization
          schema:
            $ref: "#/definitions/NoAuthResponse" 
        "500" : 
          description: Internal Server Error     
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  BadRequestResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
  NoAuthResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      transactions:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            date:
              type: string
            description:
              type: string
            amount:
              type: string
            balance:
              type: string
            details:
              type: object
              properties:
                type:
                  type: string
                category:
                  type: array
                  items:
                    type: string
            note:
              type: string
  SingleTransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      transactions:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            date:
              type: string
            description:
              type: string
            amount:
              type: string
            balance:
              type: string
            details:
              type: object
              properties:
                type:
                  type: string
                category:
                  type: array
                  items:
                    type: string
            note:
              type: string
  TransactionsResponse:
    type: array
    items:
      type: object
      properties:
        id:
          type: integer
        date:
          type: string
        description:
          type: string
        amount:
          type: string
        balance:
          type: string
        details:
          type: object
          properties:
            type:
              type: string
            category:
              type: array
              items:
                type: string   



